/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Blockchain.Crypto.SymmetricEncryption;
import Blockchain.DigitalSignature.DigitalSignature;
import Blockchain.DigitalSignature.SignatureKeyPair;
import Class.Parcel;
import Class.User;
import Utils.Utils;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.security.Key;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUN WEI
 */
public class ManagePackageGUI extends javax.swing.JFrame {
    List<String> result = new ArrayList();
    User currentUser;
    /**
     * Creates new form AcceptPackageGUI
     */
    public ManagePackageGUI() {
        initComponents();
        refresh();
    }
    
    public ManagePackageGUI(User currentUser) {
        initComponents();
        refresh();
        initialisedDocumentListener();
        this.currentUser = currentUser;
    }
    
    private void refresh() {
        DefaultTableModel tableModel = (DefaultTableModel)packagesTable.getModel();
        tableModel.setRowCount(0);
        loadTable();
        viewPackageButton.setEnabled(false);
        updateDeliveryStatusButton.setEnabled(false);
    }
    
    private void loadTable() {
        SymmetricEncryption symm = new SymmetricEncryption();
        DefaultTableModel tableModel = (DefaultTableModel)packagesTable.getModel();
        try {
            File myObj = new File("database/Parcel.txt");
            Scanner readFile = new Scanner(myObj);
            while (readFile.hasNextLine()) {
                String line = readFile.nextLine().toString();
//                if(line.contains("Processing")){
                    result.add(line);
//                };
            }
            readFile.close();
            System.out.println(result);
            for(int i=0; i<result.size();i++){
                String getColumn = result.get(i);
                String[] column = getColumn.split("!");
                
                String secretKey = column[15];
                byte[] decodeKey = Base64.getDecoder().decode(secretKey);
                Key decryptKey = new SecretKeySpec(decodeKey,0,decodeKey.length,"AES");
               
                String packageNo;
                try {
                    packageNo = column[0];
                
                    String sender = symm.decrypt(column[1],decryptKey);
                    String receiver = symm.decrypt(column[4],decryptKey);
                    String deliveryType = symm.decrypt(column[8],decryptKey);
                    String escrowFee = symm.decrypt(column[9],decryptKey);
                    String status = column[14];
                            //symm.decrypt(column[14],decryptKey);
                    
                
                Object[] row = {packageNo, sender, receiver, deliveryType,escrowFee,status};
                tableModel.addRow(row);
                } catch (Exception ex) {
                    Logger.getLogger(ManagePackageGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            result.clear();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        packagesTable = new javax.swing.JTable();
        homeLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        packageNoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        senderNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        receipientNameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        deliveryTypeTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        deliveryStatusComboBox = new javax.swing.JComboBox<>();
        viewPackageButton = new javax.swing.JButton();
        updateDeliveryStatusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        packagesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Package No", "Sender Name", "Receipient Name", "Delivery Type", "Escrow Fee", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        packagesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packagesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(packagesTable);

        homeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeLabel.setText("Home");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Manage Parcel");

        jLabel1.setText("refresh");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("PackageNo:");

        packageNoTextField.setEditable(false);

        jLabel7.setText("Sender Name:");

        senderNameTextField.setEditable(false);

        jLabel8.setText("Receipient Name:");

        receipientNameTextField.setEditable(false);

        jLabel9.setText("Delivery Type:");

        deliveryTypeTextField.setEditable(false);

        jLabel10.setText("Status:");

        statusTextField.setEditable(false);

        jLabel11.setText("Update Status:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(8, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deliveryTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(receipientNameTextField)
                            .addComponent(senderNameTextField)
                            .addComponent(packageNoTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusTextField)
                            .addComponent(deliveryStatusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(packageNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(senderNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(receipientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(deliveryTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37))
        );

        viewPackageButton.setText("View Package");
        viewPackageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPackageButtonMouseClicked(evt);
            }
        });
        viewPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPackageButtonActionPerformed(evt);
            }
        });

        updateDeliveryStatusButton.setText("Update Status");
        updateDeliveryStatusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateDeliveryStatusButtonMouseClicked(evt);
            }
        });
        updateDeliveryStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeliveryStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(327, 327, 327))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(142, 142, 142))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(363, 363, 363)
                                        .addComponent(homeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(logoutLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewPackageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(updateDeliveryStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homeLabel)
                            .addComponent(logoutLabel))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateDeliveryStatusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPackageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void packagesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packagesTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)packagesTable.getModel();
        int selectedItemRowIndex = packagesTable.getSelectedRow();
        
        packageNoTextField.setText(model.getValueAt(selectedItemRowIndex, 0).toString());
        senderNameTextField.setText(model.getValueAt(selectedItemRowIndex, 1).toString());
        receipientNameTextField.setText(model.getValueAt(selectedItemRowIndex, 2).toString());
        deliveryTypeTextField.setText(model.getValueAt(selectedItemRowIndex, 3).toString());
        statusTextField.setText(model.getValueAt(selectedItemRowIndex, 5).toString());
    }//GEN-LAST:event_packagesTableMouseClicked

    private void viewPackageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPackageButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)packagesTable.getModel();
        int selectedItemRowIndex = packagesTable.getSelectedRow();
        
        String packageNo = model.getValueAt(selectedItemRowIndex, 0).toString();
        String senderName = model.getValueAt(selectedItemRowIndex, 1).toString();
        String receipientName = model.getValueAt(selectedItemRowIndex, 2).toString();
        
        Parcel parcel = new Parcel(packageNo, senderName, receipientName);
        
        new ParcelGUI(parcel,currentUser).setVisible(true);
        dispose();
    }//GEN-LAST:event_viewPackageButtonMouseClicked

    private void updateDeliveryStatusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDeliveryStatusButtonMouseClicked
        // TODO add your handling code here:
        String selectedDeliveryStatus = String.valueOf(deliveryStatusComboBox.getSelectedItem());
        int confirm = JOptionPane.showConfirmDialog(null, String.format("Are you sure you want to edit parcel delivery status to '"+selectedDeliveryStatus +" '?" ), "Confirm Edit", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel)packagesTable.getModel();
            int selectedItemRowIndex = packagesTable.getSelectedRow();
        
            String packageNo = model.getValueAt(selectedItemRowIndex, 0).toString();
            String senderName = model.getValueAt(selectedItemRowIndex, 1).toString();
            String receipientName = model.getValueAt(selectedItemRowIndex, 2).toString();
        
            Parcel parcel = new Parcel(packageNo, senderName, receipientName);
            try {
                if(Utils.updateDeliveryStatus(parcel, selectedDeliveryStatus )==true){
                    JOptionPane.showMessageDialog(null, "Parcel delivery status has been successfully updated to '"+selectedDeliveryStatus +" '!");
                    if(selectedDeliveryStatus.equals("Delivered")){
                        String fee = model.getValueAt(selectedItemRowIndex, 4).toString();
                        new MakePaymentGUI(currentUser,fee,senderName,packageNo,"Item Delivered Releasing Money").setVisible(true);
                        
                    }
                    else if(selectedDeliveryStatus.equals("Completed")){
                        Utils.addNewBlock(packageNo);
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(ManagePackageGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            refresh();
        }
    }//GEN-LAST:event_updateDeliveryStatusButtonMouseClicked

    private void updateDeliveryStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeliveryStatusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDeliveryStatusButtonActionPerformed

    private void viewPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPackageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPackageButtonActionPerformed

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        // TODO add your handling code here:
        new UserHomeGUI(currentUser).setVisible(true);
        dispose();
    }//GEN-LAST:event_homeLabelMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        new LoginGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePackageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePackageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePackageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePackageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePackageGUI().setVisible(true);
            }
        });
    }
    
    private void initialisedDocumentListener() {
        DocumentListener inputListener = new DocumentListener() {
            private void updateButtonState() {
                boolean inputsFilled = Utils.textFieldsFilled(packageNoTextField,senderNameTextField,receipientNameTextField,deliveryTypeTextField,statusTextField);
                viewPackageButton.setEnabled(inputsFilled);
                updateDeliveryStatusButton.setEnabled(inputsFilled);
                if(statusTextField.getText().equals("Escrow Agreement Process")){
                    deliveryStatusComboBox.removeAllItems();
                    updateDeliveryStatusButton.setEnabled(false);
                }
                else if(statusTextField.getText().equals("Escrow Agreement Process Complete")){
                    deliveryStatusComboBox.removeAllItems();
                    deliveryStatusComboBox.addItem("In Sorting Facility");
                }
                else if(statusTextField.getText().equals("In Sorting Facility")){
                    deliveryStatusComboBox.removeAllItems();
                    deliveryStatusComboBox.addItem("Delivering");
                }
                else if(statusTextField.getText().equals("Delivering")){
                    deliveryStatusComboBox.removeAllItems();
                    deliveryStatusComboBox.addItem("Delivered");
                }
                else if(statusTextField.getText().equals("Delivered")){
                    deliveryStatusComboBox.removeAllItems();
                    deliveryStatusComboBox.addItem("Completed");
                }
                else{
                    deliveryStatusComboBox.removeAllItems();
                    updateDeliveryStatusButton.setEnabled(false);
                }
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateButtonState();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateButtonState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateButtonState();
            }

        };

        receipientNameTextField.getDocument().addDocumentListener(inputListener);
        packageNoTextField.getDocument().addDocumentListener(inputListener);
        senderNameTextField.getDocument().addDocumentListener(inputListener);
        deliveryTypeTextField.getDocument().addDocumentListener(inputListener);
        statusTextField.getDocument().addDocumentListener(inputListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> deliveryStatusComboBox;
    private javax.swing.JTextField deliveryTypeTextField;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JTextField packageNoTextField;
    private javax.swing.JTable packagesTable;
    private javax.swing.JTextField receipientNameTextField;
    private javax.swing.JTextField senderNameTextField;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JButton updateDeliveryStatusButton;
    private javax.swing.JButton viewPackageButton;
    // End of variables declaration//GEN-END:variables
}
