/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Class.User;
import Utils.Utils;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUN WEI
 */
public class ManageEscrowGUI extends javax.swing.JFrame {
    List<String> result = new ArrayList();
    User currentUser;
    /**
     * Creates new form ManageEscrow
     */
    public ManageEscrowGUI() {
        initComponents();
    }
    
    public ManageEscrowGUI(User currentUser) {
        initComponents();
        this.currentUser = currentUser;
        loadEscrowAgreementTable();
        viewEscrowAgreementButton.setEnabled(false);
    }
    
    public void loadEscrowAgreementTable(){
        String databaseFolder = "database/";
        String escrowAgreementFile = databaseFolder+"EscrowAgreement.txt";
        DefaultTableModel tableModel = (DefaultTableModel)escrowAgreementTable.getModel();
        if(currentUser.getFirstName().equals("Admin")){
            try {
            File myObj = new File(escrowAgreementFile);
            Scanner readFile = new Scanner(myObj);
            while (readFile.hasNextLine()) {
                String line = readFile.nextLine().toString();
                result.add(line);
                
            }
            readFile.close();
            for(int i=0; i<result.size();i++){
                String getColumn = result.get(i);
                String[] column = getColumn.split("!");
                if(column.length>1){
                String packageNo = column[0];
                String sender = column[1];
                String receiver = column[3];
                String status = column[7];

                Object[] row = {packageNo, sender, receiver,status};
                tableModel.addRow(row);
            }
            }
            result.clear();
            } catch (FileNotFoundException e) {
            e.printStackTrace();
            }
        }else{
            try {
            File myObj = new File(escrowAgreementFile);
            Scanner readFile = new Scanner(myObj);
            while (readFile.hasNextLine()) {
                String line = readFile.nextLine().toString();
                if(line.contains(currentUser.getFirstName())){
                    result.add(line);
                };
            }
            readFile.close();
            for(int i=0; i<result.size();i++){
                String getColumn = result.get(i);
                String[] column = getColumn.split("!");
                if(column.length>1){
                String packageNo = column[0];
                String sender = column[1];
                String receiver = column[3];
                String status = column[7];

                Object[] row = {packageNo, sender, receiver,status};
                tableModel.addRow(row);
            }
            }
            result.clear();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        escrowAgreementTable = new javax.swing.JTable();
        viewEscrowAgreementButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeLabel.setText("Home");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeLabel)
                .addGap(55, 55, 55)
                .addComponent(logoutLabel)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLabel)
                    .addComponent(logoutLabel))
                .addContainerGap())
        );

        escrowAgreementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Package No", "Sender", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        escrowAgreementTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrowAgreementTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(escrowAgreementTable);

        viewEscrowAgreementButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewEscrowAgreementButton.setText("View Agreement");
        viewEscrowAgreementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewEscrowAgreementButtonMouseClicked(evt);
            }
        });
        viewEscrowAgreementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEscrowAgreementButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manage Escrow Agreement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewEscrowAgreementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewEscrowAgreementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewEscrowAgreementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEscrowAgreementButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEscrowAgreementButtonActionPerformed

    private void escrowAgreementTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrowAgreementTableMouseClicked
        // TODO add your handling code here:
        viewEscrowAgreementButton.setEnabled(true);
    }//GEN-LAST:event_escrowAgreementTableMouseClicked

    private void viewEscrowAgreementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEscrowAgreementButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)escrowAgreementTable.getModel();
        int selectedItemRowIndex = escrowAgreementTable.getSelectedRow();
        
        String packageNo = (model.getValueAt(selectedItemRowIndex, 0).toString());
        new EscrowAgreementGUI(currentUser, packageNo).setVisible(true);
        dispose();
    }//GEN-LAST:event_viewEscrowAgreementButtonMouseClicked

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        // TODO add your handling code here:
        if(currentUser.getFirstName().equals("Admin")){
            new AdminGUI(currentUser).setVisible(true);
            dispose();
        }
        else{
            new UserHomeGUI(currentUser).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_homeLabelMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        new LoginGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEscrowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEscrowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEscrowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEscrowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEscrowGUI().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable escrowAgreementTable;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JButton viewEscrowAgreementButton;
    // End of variables declaration//GEN-END:variables
}
